### PR TITLE
Flat i18n text widget argument structure

### PR DESCRIPTION
**Pull request by gonuit**
### Breaking changes

* Removed `child` arguement from `I18nText` widget and replaced it with `Text` widget arguments:

  Instead of doing:
  ```dart
  I18nText(
    "my.translation.key",
    child: Text(
      "",
      style: TextStyle(fontSize: 24, color: Colors.white),
      textAlign: TextAlign.center,
    ),
  );
  ```
  You can flatten structure and remove redundant empty string argument:
  ```dart
  I18nText(
    "my.translation.key",
    style: TextStyle(fontSize: 24, color: Colors.white),
    textAlign: TextAlign.center,
  );
  ```

* Replaced `I18nPlural` widget with `I18nText.plural` widget constructor:
  
  Old way:
  ```dart
  I18nPlural(
    "my.translation.key",
    2,
    child: Text(
      "",
      style: TextStyle(fontSize: 24, color: Colors.white),
      textAlign: TextAlign.center,
    ),
  );
  ```
  Now:
  ```dart
  I18nText.plural(
    "my.translation.key",
    2,
    style: TextStyle(fontSize: 24, color: Colors.white),
    textAlign: TextAlign.center,
  );
  ```

* Suggested new package version

### CODE REVIEW

**Comment by ilteoood** [comment]
Hi @gonuit,
thank you for your PR, but this implementation remove current features.

This is the constructor of the text widget:
Text(String data, {Key key, TextStyle style, StrutStyle strutStyle, TextAlign textAlign, TextDirection textDirection, Locale locale, bool softWrap, TextOverflow overflow, double textScaleFactor, int maxLines, String semanticsLabel, TextWidthBasis textWidthBasis})

With this PR you are removing, for example, the ability to set the textScaleFactor.
Adding all of these parameter to the I18nText/I18nPlural constructor will hard link them to the one provided by Text: everytime that Text will remove/add a parameter, I must update the library to keep them updated.

I don't want this.

In this way, following the child approach of flutter, we can decouple the content of the Text widget and the content my widgets.

**Comment by ilteoood** [comment]
Hi @defint,
What do you think about this PR?
@gonuit made these changed because he thinks that Text("", ...) is "too weird".

**Comment by defint** [comment]
Hi @ilteoood 

I think that both solutions are very strange.
In my current project I have separate widget to show text, I don't use `Text` directly. Your solutions forces me to use `Text` and I can't use something different.

I propose to use  builder behaviour instead of child behaviour.

Here is example:
```dart
I18nPlural("clicked.times", clicked, (msg) => Text(msg)),
```

example implementations:
```
typedef I18nPluralBuilder = Widget Function(String message);

class I18nPlural extends StatelessWidget {
  final String _key;
  final I18nPluralBuilder _builder;
  final int _pluralValue;

  const I18nPlural(this._key, this._pluralValue, this._builder);

  @override
  Widget build(BuildContext context) =>
      _builder(FlutterI18n.plural(context, _key, _pluralValue));
}
```

In this case I can use `MySuperCustomTextWidget` :)

**Comment by ilteoood** [comment]
Hi @defint ,
this solution is cleaner when you want to use different type of widgets, but I don't see any advantage to use that builder and the standard form with

```
Text(FlutterI18n.translate(..., ...))
```

**Comment by defint** [comment]
@ilteoood 

In my case: 
I will never use this widgets, because each big/medium project has own component to show text and I created something similar to widget that I provide above.

In general case:
This widgets are redundant and can be used only for very small project and I think we can let it be as it is.

**Pull request closed without merging**
