### PR TITLE
https://github.com/ilteoood/flutter_i18n/issues/17

### PR DESCRIPTION
**Pull request by jlcool**

### CODE REVIEW

**Comment by jlcool** [comment]
Just to illustrate the problem, I don't know how to modify it.

**Comment by ilteoood** [comment]
If this is an example of how you use the library, you are using it in the wrong way. Check the example.

**Comment by jlcool** [comment]
Did you see my revision? Do you agree with me that this problem exists? This really fixes the problem I'm talking about, but I don't know if it's optimal.

**Comment by ilteoood** [comment]
I saw it, but this is not the way how the delegates work.

**Comment by jlcool** [comment]
If there is no better way, I temporarily use it in my own project.

**Comment by hyperpanthera** [comment]
@jlcool He is a jerk. Does not want to fix the black screen problem.

**Pull request closed without merging**
